// Mocks generated by Mockito 5.4.2 from annotations
// in match_42/test/mypage_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:match_42/data/user.dart' as _i2;
import 'package:match_42/service/block_service.dart' as _i3;
import 'package:match_42/service/interest_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BlockService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockService extends _i1.Mock implements _i3.BlockService {
  @override
  String get rootUrl => (super.noSuchMethod(
        Invocation.getter(#rootUrl),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  set rootUrl(String? _rootUrl) => super.noSuchMethod(
        Invocation.setter(
          #rootUrl,
          _rootUrl,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<_i2.User> addBlockUser(
    String? intraId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBlockUser,
          [
            intraId,
            token,
          ],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #addBlockUser,
            [
              intraId,
              token,
            ],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #addBlockUser,
            [
              intraId,
              token,
            ],
          ),
        )),
      ) as _i4.Future<_i2.User>);
  @override
  _i4.Future<_i2.User> deleteBlockUser(
    String? intraId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBlockUser,
          [
            intraId,
            token,
          ],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #deleteBlockUser,
            [
              intraId,
              token,
            ],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #deleteBlockUser,
            [
              intraId,
              token,
            ],
          ),
        )),
      ) as _i4.Future<_i2.User>);
}

/// A class which mocks [InterestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInterestService extends _i1.Mock implements _i5.InterestService {
  @override
  _i4.Future<List<String>> getInterestsById(
    int? userId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInterestsById,
          [
            userId,
            token,
          ],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);
  @override
  _i4.Future<_i2.User> postInterests(
    List<String>? interests,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postInterests,
          [
            interests,
            token,
          ],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #postInterests,
            [
              interests,
              token,
            ],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #postInterests,
            [
              interests,
              token,
            ],
          ),
        )),
      ) as _i4.Future<_i2.User>);
}
