name: Build
on: 
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true


      - name: Java Setup
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Copy Application-Properties
        run: |
          cp match42-secret/.env .


      - name: Pub Get Packages
        run: flutter pub get

      - name: Run Unit Test
        run: flutter test

      - name: 테스트 결과를 PR에 코멘트로 등록합니다
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'


      # - name: Upload Apk
      #   uses: actions/upload-artifact@v3.1.2
      #   with:
      #     name: android_debug_apk
      #     path: build/app/outputs/flutter-apk/app-debug.apk
