name: Build
on: workflow_dispatch

jobs:
  build:
    runs-on: linux-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Java Setup
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Pub Get Packages
        run: flutter pub get

      - name: Build Dev Apk
        run: flutter build apk --debug

      - name: Upload Apk
        uses: actions/upload-artifact@v3.1.2
        with:
          name: android_debug_apk
          path: build/app/outputs/flutter-apk/app-debug.apk
